### PR TITLE
Fix: Allow LazyListener to work with callables fetched from container

### LINKED ISSUE #22: Please allow for callables not just ListenerInterface
Event allows for callables, so league-lazy-event should as well. Otherwise I now have to change my listeners just to have lazy loading.

Thanks!

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] asserts that the `LazyListener` works fine when the actual listener fetched from the container is a callable
* [x] adjusts the `LazyListener` to properly handle a listener when it is a callable

Fixes #22.

### CODE REVIEW

**Comment by localheinz** [comment]
@nesl247

Do you want to take a look?

File: src/LazyListener.php [hunk 1]
```diff
@@ -49,16 +50,30 @@ public function getListener()
...
-
-            $this->listener = $listener;
+            $this->listener = $this->ensureListener($listener);
         }
 
         return $this->listener;
     }
 
+    /**
+     * @param mixed $listener
```
Comment (nesl247) [inline src/LazyListener.php]: Should probably be `callable|ListenerInterface`.

**Comment by nesl247** [comment]
I like it!

File: src/LazyListener.php (hunk 1 above)
Comment (localheinz) [inline src/LazyListener.php]: @nesl247 

You're right when looking at [`League\Event\Emitter::ensureListener()`](https://github.com/thephpleague/event/blob/master/src/Emitter.php#L97-L117), but it could be anything, actually!

Maybe worth submitting a PR about the docblock in `league/event`.

Comment (nesl247) [inline src/LazyListener.php]: It could be anything, but it's about what types you expect. We only expect either a `callable` or `ListenerInterface`. If you could do multiple typehints, we actually would rather than throwing an exception.

**Comment by localheinz** [comment]
Thank you, @nesl247!
